name: AI PR Review
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to review"
        required: true
        default: "main"
      dry_run:
        description: "Don't post comments (true/false)"
        required: false
        default: "true"
        
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: AI review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
          OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: python .github/ai_review.py

